/// Flutter icons Comment
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Comment
///      fonts:
///       - asset: fonts/Comment.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Comment {
  Comment._();

  static const _kFontFam = 'Comment';
  static const String? _kFontPkg = null;

  static const IconData customicons = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
